# Generated by Django 6.0.2 on 2026-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(help_text='e.g. University of Michigan, Codio, Packt', max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, help_text='Leave blank if it does not expire', null=True)),
                ('credential_id', models.CharField(blank=True, default='', max_length=100)),
                ('credential_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='description_bullets',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of bullet points for rendering on the frontend'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='technologies_used',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Python", "Django", "AWS"]'),
        ),
    ]
