# Generated by Django 6.0.2 on 2026-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_experience_description_bullets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for tag pill, e.g. #3b82f6', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown in listing cards (1-2 sentences)')),
                ('cover_image', models.URLField(blank=True, default='', help_text='URL for cover / hero image')),
                ('blocks', models.JSONField(default=list, help_text='Array of content block objects (see model docstring for format)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically when status → Published; can be overridden', null=True)),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes (auto-calculated on save)')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('likes', models.PositiveIntegerField(default=0, editable=False)),
                ('featured', models.BooleanField(default=False, help_text='Show as featured / hero post in the blog listing')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual sort order')),
                ('seo_title', models.CharField(blank=True, default='', help_text='Override <title> tag (max 60 chars; falls back to title)', max_length=60)),
                ('seo_description', models.CharField(blank=True, default='', help_text='Meta description (max 160 chars; falls back to excerpt)', max_length=160)),
                ('og_image', models.URLField(blank=True, default='', help_text='OpenGraph image URL (falls back to cover_image)')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='portfolio.blogtag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
